apiVersion: v2
description: A Helm Chart to deploy the sfd-helm-ingress application to Kubernetes
name: ffc-demo-ingress
# this version is automatically updated in the build pipeline
version: 1.0.8
dependencies:
- name: adp-helm-library
  version: ^1.0.0
  repository: https://raw.githubusercontent.com/defra/adp-helm-repository/main/adp-helm-library
